/*
 * This file is generated by jOOQ.
 */
package org.jease.entity.tables.records;


import org.jease.entity.tables.Parameter;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParameterRecord extends UpdatableRecordImpl<ParameterRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -220650299;

    /**
     * Setter for <code>jease.parameter.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jease.parameter.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jease.parameter.param_key</code>.
     */
    public void setParamKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jease.parameter.param_key</code>.
     */
    public String getParamKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jease.parameter.param_value</code>.
     */
    public void setParamValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jease.parameter.param_value</code>.
     */
    public String getParamValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Parameter.PARAMETER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Parameter.PARAMETER.PARAM_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Parameter.PARAMETER.PARAM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getParamKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getParamValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getParamKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParamValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParameterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParameterRecord value2(String value) {
        setParamKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParameterRecord value3(String value) {
        setParamValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParameterRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParameterRecord
     */
    public ParameterRecord() {
        super(Parameter.PARAMETER);
    }

    /**
     * Create a detached, initialised ParameterRecord
     */
    public ParameterRecord(Integer id, String paramKey, String paramValue) {
        super(Parameter.PARAMETER);

        set(0, id);
        set(1, paramKey);
        set(2, paramValue);
    }
}
