/*
 * This file is generated by jOOQ.
 */
package org.jease.entity;


import org.jease.entity.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>jease</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTENT_PRIMARY = Indexes0.CONTENT_PRIMARY;
    public static final Index LINKCHECK_PRIMARY = Indexes0.LINKCHECK_PRIMARY;
    public static final Index PARAMETER_PRIMARY = Indexes0.PARAMETER_PRIMARY;
    public static final Index REDIRECT_PRIMARY = Indexes0.REDIRECT_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index SEQUENCE_PRIMARY = Indexes0.SEQUENCE_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index VERSION_PRIMARY = Indexes0.VERSION_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONTENT_PRIMARY = Internal.createIndex("PRIMARY", Content.CONTENT, new OrderField[] { Content.CONTENT.ID }, true);
        public static Index LINKCHECK_PRIMARY = Internal.createIndex("PRIMARY", Linkcheck.LINKCHECK, new OrderField[] { Linkcheck.LINKCHECK.ID }, true);
        public static Index PARAMETER_PRIMARY = Internal.createIndex("PRIMARY", Parameter.PARAMETER, new OrderField[] { Parameter.PARAMETER.ID }, true);
        public static Index REDIRECT_PRIMARY = Internal.createIndex("PRIMARY", Redirect.REDIRECT, new OrderField[] { Redirect.REDIRECT.ID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index SEQUENCE_PRIMARY = Internal.createIndex("PRIMARY", Sequence.SEQUENCE, new OrderField[] { Sequence.SEQUENCE.ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index VERSION_PRIMARY = Internal.createIndex("PRIMARY", Version.VERSION, new OrderField[] { Version.VERSION.ID }, true);
    }
}
