/*
 * This file is generated by jOOQ.
 */
package org.jease.entity.tables;


import org.jease.entity.Indexes;
import org.jease.entity.Jease;
import org.jease.entity.Keys;
import org.jease.entity.tables.records.ParameterRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parameter extends TableImpl<ParameterRecord> {

    private static final long serialVersionUID = 1591907636;

    /**
     * The reference instance of <code>jease.parameter</code>
     */
    public static final Parameter PARAMETER = new Parameter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParameterRecord> getRecordType() {
        return ParameterRecord.class;
    }

    /**
     * The column <code>jease.parameter.id</code>.
     */
    public final TableField<ParameterRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jease.parameter.param_key</code>.
     */
    public final TableField<ParameterRecord, String> PARAM_KEY = createField("param_key", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>jease.parameter.param_value</code>.
     */
    public final TableField<ParameterRecord, String> PARAM_VALUE = createField("param_value", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>jease.parameter</code> table reference
     */
    public Parameter() {
        this(DSL.name("parameter"), null);
    }

    /**
     * Create an aliased <code>jease.parameter</code> table reference
     */
    public Parameter(String alias) {
        this(DSL.name(alias), PARAMETER);
    }

    /**
     * Create an aliased <code>jease.parameter</code> table reference
     */
    public Parameter(Name alias) {
        this(alias, PARAMETER);
    }

    private Parameter(Name alias, Table<ParameterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parameter(Name alias, Table<ParameterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Parameter(Table<O> child, ForeignKey<O, ParameterRecord> key) {
        super(child, key, PARAMETER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jease.JEASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARAMETER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ParameterRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PARAMETER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParameterRecord> getPrimaryKey() {
        return Keys.KEY_PARAMETER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParameterRecord>> getKeys() {
        return Arrays.<UniqueKey<ParameterRecord>>asList(Keys.KEY_PARAMETER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parameter as(String alias) {
        return new Parameter(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parameter as(Name alias) {
        return new Parameter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parameter rename(String name) {
        return new Parameter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Parameter rename(Name name) {
        return new Parameter(name, null);
    }
}
